LISAMINDBLADE_ASSISTANT_ENGINE=openclaw \
LISAMINDBLADE_OPENCLAW_CLIENT_MODE=cli \
LISAMINDBLADE_OPENCLAW_CLI_USE_LOCAL=true \
LISAMINDBLADE_OPENCLAW_CLI_TIMEOUT_SECONDS=180 \
LISAMINDBLADE_SHARED_TOKEN=mindblade \
LISAMINDBLADE_TTS_ENGINE=stub \
python3 -m app.main
